### ISSUE TITLE
Logistic Stations not mining on a specific planet

### ISSUE THREAD

**Issue by jml3on** [blacksnipebiu/PlanetMiner#1]
In the attached save file, new stations do not mine.

This is the first time I see this problem. The only thing different with this planet is that I dropped and copy/pasted a lot of foundations, which I don't normally do.

Stations at the pole are mining ok, but where added before most of the foundations (if I remember correctly). Only new stations cannot mine.

On any other planet, new stations mine just fine.

save file is here: https://drive.google.com/file/d/1jx80zlmm2asZWmilS6PJAh0QpHrusJZj/view?usp=sharing

**Comment by jml3on** [comment]
Actually, I just realized that if I either a) give power to the 4 other stations feeding the smelters that are currently not powered, or b) delete all those 4 ILSes, then the station next to the mech starts working.

So it's an issue related to unpowered stations. not related to foundations.

**Comment by jml3on** [comment]
It seems if there is unpowered ILS switched in demand mode, it blocks the station next to the mech.

switching it to 'storage' makes the mech station work again.

**Comment by jml3on** [comment]
my guess is line 101


                                if (stationComponent.energy < 20000000L) return;

is causing the issue, as it stops looping through the stations.

**Comment by blacksnipebiu** [comment]
> my guess is line 101
> 
> ```
>                             if (stationComponent.energy < 20000000L) return;
> ```
> 
> is causing the issue, as it stops looping through the stations.

yes,you are right.I have updated this part of the bug in version 3.0.5.

**Comment by jml3on** [comment]
yes, that fixed it.

Thanks for the super quick fix!
