### ISSUE TITLE
Fuel is not consumed correctly

### ISSUE THREAD

**Issue by whusc86** [blacksnipebiu/PlanetMiner#3]
line 90 @ PlanetMiner.cs:
    sc.storage[k].count -= needcount;
Should be:
    stationStore2.count.count -= needcount;

**Comment by whusc86** [comment]
Should be:
sc.storage[sc.storage.Length - 2].count -= needcount;

**Comment by blacksnipebiu** [comment]
Ok，I will repair this problem this evening

**Comment by blacksnipebiu** [comment]
Thanks for your feedback, I have fixed this issue
